/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unipar.views;

import DTOItemVneda.ItemVendaDTOTest;
import DTOItemVneda.VendaDTO;
import DTOItemVneda.VendaResponse;
import br.unipar.models.Cliente;
import br.unipar.models.ItemVenda;
import br.unipar.models.Produto;
import br.unipar.models.Venda;
import br.unipar.retrofit.RetrofitConfig;
import br.unipar.services.ApiService;
import dto.ItemVendaDTO;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author lucia
 */
public class VendaFrame extends javax.swing.JFrame {
    private JTable clientesTable;
    private ApiService apiService;
    private List<ItemVenda> itensVenda;
    private List<Produto> produtos;
    private DefaultTableModel itensVendaModel;
    private ClientePanel clientePanel;
    /**
     * Creates new form VendaFrame
     */
    public VendaFrame() {
        initComponents();
        apiService = RetrofitConfig.getApiService();
        
        itensVenda = new ArrayList<>();
        produtos = new ArrayList<>();
        clientePanel = new ClientePanel(this); 
        listarProdutos();
        refreshListas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textFieldCliente = new javax.swing.JTextField();
        btnAddCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemVendaModel = new javax.swing.JTable();
        btnFimVenda = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de vendas");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Cliente");

        textFieldCliente.setEditable(false);
        textFieldCliente.setText("cliente selecionado");
        textFieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldClienteActionPerformed(evt);
            }
        });

        btnAddCliente.setText("Adicionar Cliente");
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(textFieldCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCliente)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCliente))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Lista de produtos");

        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Valor", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtosTable.setColumnSelectionAllowed(true);
        produtosTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(produtosTable);
        produtosTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (produtosTable.getColumnModel().getColumnCount() > 0) {
            produtosTable.getColumnModel().getColumn(0).setResizable(false);
            produtosTable.getColumnModel().getColumn(1).setResizable(false);
            produtosTable.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAddItem.setText("Adicionar Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddItem)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAddItem)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Carrinho");

        itemVendaModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descricao", "Quantidade", "Total"
            }
        ));
        itemVendaModel.setColumnSelectionAllowed(true);
        itemVendaModel.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(itemVendaModel);
        itemVendaModel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnFimVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFimVenda.setText("Finalizar Venda");
        btnFimVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimVendaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total da Venda");

        jTextField2.setEditable(false);
        jTextField2.setText("00.00");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemover))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFimVenda))))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFimVenda)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldClienteActionPerformed

    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        clientePanel = new ClientePanel(this); // Atribui a nova instância de ClientePanel ao campo clientePanel
        clientePanel.setVisible(true); // Torna o clientePanel visível
    }//GEN-LAST:event_btnAddClienteActionPerformed

    private void btnFimVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimVendaActionPerformed
        Cliente cliente = clientePanel.getSelectedCliente();
        realizarVendaAssincrona(cliente);
    }//GEN-LAST:event_btnFimVendaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        RemoveritemVenda();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        adicionarItemVenda();
    }//GEN-LAST:event_btnAddItemActionPerformed


    private void listarProdutos() {
    // Simulate an API call to load products
    ApiService apiService = RetrofitConfig.getApiService();
    apiService.listarProdutos().enqueue(new Callback<List<Produto>>() {
        @Override
        public void onResponse(Call<List<Produto>> call, Response<List<Produto>> response) {
            if (response.isSuccessful() && response.body() != null) {
                produtos = response.body(); // Atualiza a lista de produtos da classe VendaFrame

                SwingUtilities.invokeLater(() -> {
                    // Criar modelo de tabela com as colunas apropriadas
                    DefaultTableModel defaultTableModel = new DefaultTableModel();
                    defaultTableModel.addColumn("Descrição");
                    defaultTableModel.addColumn("Valor");
                    defaultTableModel.addColumn("Categoria");

                    // Adicionar os produtos ao modelo da tabela
                    for (Produto produto : produtos) {
                        defaultTableModel.addRow(new Object[]{
                            produto.getDescricao(), produto.getValor(), produto.getCategoria()
                        });
                    }

                    // Definir o modelo da tabela de produtos
                    produtosTable.setModel(defaultTableModel);
                });
                registrarLog("Obtenção dos produtos","Sucesso"); // Corrigido: o log indica sucesso
            } else {
                // Se ocorrer um erro na resposta da API, exibir uma mensagem de erro
                JOptionPane.showMessageDialog(VendaFrame.this, "Failed to load products.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        @Override
        public void onFailure(Call<List<Produto>> call, Throwable t) {
            // Em caso de falha na chamada à API, exibir uma mensagem de erro
            JOptionPane.showMessageDialog(VendaFrame.this, "Error: " + t.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    });
}

    

    private void RemoveritemVenda(){
        int rowselected = itemVendaModel.getSelectedRow();
        itensVendaModel.removeRow(rowselected);
    }
    

    private void adicionarItemVenda() {
        int produtoIndex = produtosTable.getSelectedRow();
        
        if (produtos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lista de produtos vazia.");
        return;
        }
        
        if (produtoIndex == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto.");
            return;
        }

        Produto produto = produtos.get(produtoIndex);

        int quantidade;
        try {
            String input = JOptionPane.showInputDialog(this, "Informe a quantidade:");
            if (input == null || input.isEmpty()) {
                return; // Se o usuário cancelar ou fornecer uma entrada vazia, saia do método
            }
            quantidade = Integer.parseInt(input);
            if (quantidade <= 0) {
                JOptionPane.showMessageDialog(this, "Quantidade inválida.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantidade inválida.");
            return;
        }

        BigDecimal valorTotal = produto.getValor().multiply(new BigDecimal(quantidade));

        // Adicionar o item na tabela de itens da venda
        if (itensVendaModel == null) {
            itensVendaModel = new DefaultTableModel();
            itensVendaModel.addColumn("ID");
            itensVendaModel.addColumn("Descrição");
            itensVendaModel.addColumn("Quantidade");
            itensVendaModel.addColumn("Valor Unitário");
            itensVendaModel.addColumn("Valor Total");
        }

        itensVendaModel.addRow(new Object[]{produto.getId(),produto.getDescricao(), quantidade, produto.getValor(), valorTotal});
        
        itemVendaModel.setModel(itensVendaModel);
        
        // Adicionar o item na lista de itens da venda para posterior envio ao servidor
        ItemVenda itemVenda = new ItemVenda();
        itemVenda.setProdutoId(produto.getId()); // Aqui você define o ID do produto
        itemVenda.setQuantidade(quantidade);
        itemVenda.setValorUnitario(produto.getValor());
        itemVenda.setValorTotal(valorTotal);
        // Adicione o itemVenda à sua lista de itens de venda, que você pode enviar ao servidor quando realizar a venda
        itensVenda.add(itemVenda);
        
    }
    private void realizarVendaAssincrona(Cliente cliente) {
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente.");
            return;
        }

        ExecutorService executor = Executors.newSingleThreadExecutor();
        executor.execute(() -> {
            try {
                // Crie uma lista de DTOs de ItemVenda
                List<ItemVendaDTO> itensVendaDTO = new ArrayList<>();
                for (ItemVenda itemVenda : itensVenda) {
                    ItemVendaDTO itemVendaDTO = new ItemVendaDTO(
                            itemVenda.getQuantidade(),
                            itemVenda.getValorUnitario(),
                            itemVenda.getProdutoId()
                    );
                    itensVendaDTO.add(itemVendaDTO);
                }

                // Criar uma venda na API
                Venda venda = new Venda();
                venda.setClienteId(cliente.getId());
                venda.setItensvenda(itensVendaDTO);
                // Defina a data atual formatada para o formato desejado
                LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
                String formattedDateTime = now.format(formatter);
                venda.setData(formattedDateTime);
                VendaDTO vendatest = new VendaDTO();
                vendatest.setClienteId(cliente.getId());
                vendatest.setData(formattedDateTime);
                 // Crie uma lista de DTOs de ItemVendaDTOTest
            List<ItemVendaDTOTest> itensVendaDTOTest = new ArrayList<>();
            for (ItemVenda itemVenda : itensVenda) {
                ItemVendaDTOTest itemVendaDTOTest = new ItemVendaDTOTest(
                        itemVenda.getProdutoId(),
                        itemVenda.getValorUnitario().doubleValue(),
                        itemVenda.getQuantidade()
                );
                itensVendaDTOTest.add(itemVendaDTOTest);
            }
                vendatest.setItensVenda(itensVendaDTOTest);
                vendatest.setObservacoes("ada");
               

                // Faça a chamada assíncrona para criar a venda
                apiService.criarVenda(vendatest).enqueue(new Callback<VendaResponse>() {
    @Override
    public void onResponse(Call<VendaResponse> call, Response<VendaResponse> response) {
        if (response.isSuccessful()) {
            VendaResponse vendaCriada = response.body();
            SwingUtilities.invokeLater(() ->
                    JOptionPane.showMessageDialog(VendaFrame.this, "Venda realizada com sucesso!")
            );
            registrarLog("Inserção de venda", "Sucesso");
        } else {
            String errorMessage = "Erro ao criar venda: " + response.code() + " - " + response.message();
      
            SwingUtilities.invokeLater(() ->
                    JOptionPane.showMessageDialog(VendaFrame.this, errorMessage)
            );
            registrarLog("Inserção de venda", errorMessage);
        }
    }

    @Override
    public void onFailure(Call<VendaResponse> call, Throwable t) {
        String errorMessage = "Erro ao criar venda: " + t.getMessage();
      
        SwingUtilities.invokeLater(() ->
                JOptionPane.showMessageDialog(VendaFrame.this, errorMessage)
        );
        registrarLog("Inserção de venda", errorMessage);
    }
});
            } finally {
                executor.shutdown();
            }
        });
    }
   
   




    private void refreshListas(){
        // Atualizar automaticamente os clientes e produtos a cada 5 minutos
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                
                listarProdutos();
            }
        }, 0, 5 * 60 * 1000); // Atualiza a cada 5 minutos (5 * 60 * 1000 ms)

    }

    
    
    private void registrarLog(String operacao, String status) {
        String logFilePath = "log.txt";
        try (PrintWriter writer = new PrintWriter(new FileWriter(logFilePath, true))) {
            LocalDateTime now = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String dataHora = now.format(formatter);
            writer.println(dataHora + " - Operação: " + operacao + " - Status: " + status);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public void setClienteFields(Cliente cliente) {
        textFieldCliente.setText(cliente.getNome());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnFimVenda;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTable itemVendaModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable produtosTable;
    private javax.swing.JTextField textFieldCliente;
    // End of variables declaration//GEN-END:variables
}
